#!/bin/bash
# Simple fix: Tell user exactly what to do in Xcode

echo "🔧 Xcode Project Fix Instructions"
echo "=================================="
echo ""
echo "The files are in the correct location:"
echo "  ✅ /iosApp/iosApp/Utils/"
echo "  ✅ /iosApp/iosApp/Data/"
echo "  ✅ /iosApp/iosApp/ViewModels/"
echo ""
echo "Xcode is looking for them in the wrong location:"
echo "  ❌ /iosApp/Utils/ (doesn't exist anymore)"
echo ""
echo "QUICK FIX:"
echo "=========="
echo "1. In Xcode, close the project (Cmd+Q)"
echo "2. Delete DerivedData:"
rm -rf ~/Library/Developer/Xcode/DerivedData/iosApp-*
echo "   ✅ Deleted DerivedData"
echo ""
echo "3. Reopen Xcode:"
echo "   open iosApp/iosApp.xcworkspace"
echo ""
echo "4. In Xcode Navigator, you'll see files in RED (missing)"
echo "5. Select ALL red files, press Delete, choose 'Remove Reference'"
echo ""
echo "6. Right-click 'iosApp' group → 'Add Files to iosApp...'"
echo "7. Navigate to: iosApp/iosApp/ (note: TWO 'iosApp' in path)"
echo "8. Select: Data, Utils, ViewModels folders"
echo "9. ✅ Check 'Copy items if needed'"
echo "10. ✅ Check 'Create groups'"
echo "11. ✅ Target: iosApp"
echo "12. Click Add"
echo ""
echo "13. Cmd+Shift+K (Clean)"
echo "14. Cmd+B (Build)"
echo ""
echo "That should fix it!"
