name: iosApp
options:
  bundleIdPrefix: com.switch2go
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: CHL552XFN9
    CODE_SIGN_STYLE: Manual
  configs:
    Debug:
      CODE_SIGN_IDENTITY: "Apple Development"
    Release:
      CODE_SIGN_IDENTITY: "Apple Distribution"

targets:
  iosApp:
    type: application
    platform: iOS
    sources:
      - path: iosApp
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.switch2go.aac
        INFOPLIST_FILE: iosApp/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1,2"
        IPHONEOS_DEPLOYMENT_TARGET: "15.0"
        ENABLE_BITCODE: "NO"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
        FRAMEWORK_SEARCH_PATHS: "$(inherited) $(SRCROOT)/../shared/build/bin/iosArm64/releaseFramework $(SRCROOT)/../shared/build/bin/iosX64/releaseFramework $(SRCROOT)/../shared/build/bin/iosSimulatorArm64/releaseFramework"
        OTHER_LDFLAGS: "$(inherited) -framework VocableShared"
      configs:
        Debug:
          PROVISIONING_PROFILE_SPECIFIER: "Addison Graham Ad Hoc"
        Release:
          PROVISIONING_PROFILE_SPECIFIER: "Addison Graham App Store"
    dependencies:
      - framework: "../shared/build/bin/iosArm64/releaseFramework/VocableShared.framework"
        embed: true
        codeSign: true
    postBuildScripts:
      - name: "Embed KMP Framework"
        script: |
          # This script ensures the correct framework architecture is used
          if [ "$PLATFORM_NAME" = "iphonesimulator" ]; then
              if [ "$NATIVE_ARCH" = "arm64" ]; then
                  FRAMEWORK_PATH="${SRCROOT}/../shared/build/bin/iosSimulatorArm64/releaseFramework/VocableShared.framework"
              else
                  FRAMEWORK_PATH="${SRCROOT}/../shared/build/bin/iosX64/releaseFramework/VocableShared.framework"
              fi
          else
              FRAMEWORK_PATH="${SRCROOT}/../shared/build/bin/iosArm64/releaseFramework/VocableShared.framework"
          fi
        basedOnDependencyAnalysis: false

schemes:
  iosApp:
    build:
      targets:
        iosApp: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
